name: nyoba
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 5.8.45+5945
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter # Add this line
  hexcolor: ^2.0.7
  percent_indicator: ^4.2.2
  auto_size_text: ^3.0.0
  colorful_safe_area: ^0.3.0
  flutter_screenutil: ^5.5.3+2
  http: ^0.13.4
  loading_animations: ^2.2.0
  cached_network_image: ^3.2.1
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  flutter_countdown_timer: ^4.1.0
  fab_circular_menu: ^1.0.2
  clipboard: ^0.1.3
  carousel_slider: ^4.1.1
  intl: ^0.17.0
  flutter_widget_from_html_core: ^0.8.5+3
  introduction_screen: ^3.0.2
  shimmer: ^2.0.0
  flutter_sms: ^2.3.3
  url_launcher: ^6.1.5
  firebase_auth: ^4.2.3
  pinput: ^2.2.11
  google_sign_in: ^5.4.0
  like_button: ^2.0.4
  flutter_rating_bar: ^4.0.1
  firebase_messaging: ^14.2.0
  uni_links: ^0.5.1
  launch_review: ^3.0.1
  share_plus: ^4.0.10
  html_unescape: ^2.0.0
  youtube_player_flutter: ^8.1.0
  flutter_custom_clippers: ^2.0.0
  qr_code_scanner: ^1.0.1
  dart_ipify: ^1.1.1
  photo_view: ^0.14.0
  money2: ^3.1.3
  email_validator: ^2.1.17
  country_code_picker: ^2.0.2
  pull_to_refresh:
    git:
      url: https://github.com/miquelbeltran/flutter_pulltorefresh
  upgrader: ^4.4.2
  sign_in_with_apple: ^4.1.0
  crypto: ^3.0.2
  webview_flutter: ^3.0.4
  flutter_phoenix: ^1.0.0
  flutter_local_notifications: ^9.7.0
  path_provider: ^2.0.11
  package_info_plus: ^1.4.3
  video_player: ^2.4.5
  path: ^1.8.1
  rxdart: ^0.27.5
  animated_text_kit: ^4.2.2
  loading_animation_widget: ^1.2.0+3
  sms_autofill: ^2.2.0
  showcaseview:
    git:
      url: https://github.com/floxydio/showcase-nullsafety
      ref: master
  qr_flutter: ^4.0.0
  font_awesome_flutter: ^10.3.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  flutter_easyloading: ^3.0.5
  ntp: ^2.0.0
  permission_handler: ^9.2.0
  cloud_firestore: ^4.3.0
  wakelock: ^0.6.1+2
  tutorial_coach_mark: ^1.2.3
  card_swiper: ^2.0.4
  flutter_facebook_auth: ^4.4.0+1
  uiblock: ^2.0.2
  dotted_border: ^2.0.0+2
  image_picker: ^0.8.5+3
  firebase_core: ^2.4.0
  flutter_inappwebview: ^5.7.2+3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  internet_connection_checker: ^0.0.1+4
  connectivity_plus: ^2.3.7
  flutter_native_splash: ^2.2.5
  flutter_app_badger: ^1.5.0

  # Redeem
  lottie: ^1.4.2
  dio: ^5.1.1
  fluttertoast: ^8.2.1
  flutter_svg: ^1.1.6
  get: ^4.6.5
  google_fonts: ^3.0.1

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.9.3
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#f8f8f8"
  image: "images/icon/logo.png"

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "images/icon/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/icon/
    - images/lobby/
    - images/account/
    - images/blog/
    - images/cart/
    - images/order/
    - images/product_detail/
    - images/search/
    - i18n/en.json
    - i18n/id.json
    - i18n/es.json
    - i18n/fr.json
    - i18n/zh.json
    - i18n/ja.json
    - i18n/ko.json
    - i18n/ar.json
    - i18n/nl.json
    - i18n/pt.json
    - i18n/de.json
    - i18n/tr.json
    - i18n/iw.json
    - i18n/hi.json
    - i18n/te.json
    - i18n/ms.json
    - i18n/mng.json
    - lottie/success.json
    - lottie/failed.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 100
        - asset: fonts/Poppins-Thin.ttf
          weight: 200
        - asset: fonts/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins-Black.ttf
          weight: 800
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 900
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Italic.ttf
          style: italic
        - asset: fonts/OpenSans-Medium.ttf
          weight: 200
        - asset: fonts/OpenSans-SemiBold.ttf
          weight: 500
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
